// Coupon service — resource group scope orchestrator.
//
// Everything in docs/approach.md §6. Deploying this into an empty resource group
// produces the whole system; the pipeline adds only the database grant, the backend
// artifact, and (phase E) the frontend upload.
//
// No dependsOn appears anywhere in this file or its modules. Every ordering constraint
// is expressed as a real data dependency — a module that needs a hostname takes it as a
// parameter — so the implicit graph is the only graph.

targetScope = 'resourceGroup'

// ---------------------------------------------------------------------------
// Naming and placement
// ---------------------------------------------------------------------------

@description('Azure region for every resource. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Short project name used to build every resource name. Lowercase letters only.')
@minLength(3)
@maxLength(11)
param namePrefix string = 'couponsvc'

@description('Environment discriminator used in resource names.')
@minLength(2)
@maxLength(5)
param environmentName string = 'lab'

// Derived from the subscription ID and the resource group NAME, neither of which changes
// when the group is deleted and recreated. So these names are stable across a full
// teardown — which matters most for the storage account, whose name determines the static
// website URL and therefore the Entra redirect URI. See docs/decisions.md.
var nameSuffix = substring(uniqueString(subscription().id, resourceGroup().name), 0, 6)

var apiIdentityName = 'id-${namePrefix}-${environmentName}-api'
var gatewayIdentityName = 'id-${namePrefix}-${environmentName}-gateway'
var logAnalyticsName = 'log-${namePrefix}-${environmentName}'
var appInsightsName = 'appi-${namePrefix}-${environmentName}'
var appServicePlanName = 'plan-${namePrefix}-${environmentName}'
var appServiceName = 'app-${namePrefix}-${environmentName}-${nameSuffix}'
var sqlServerName = 'sql-${namePrefix}-${environmentName}-${nameSuffix}'
var apimServiceName = 'apim-${namePrefix}-${environmentName}-${nameSuffix}'

@description('Storage account holding the static frontend. Leave empty — as the pipeline does — for the deterministic name built from uniqueString(subscription().id, resourceGroup().name), which is reproduced identically when this resource group is deleted and recreated in the same subscription. Set it explicitly only to recover an existing static website URL that the deterministic name would no longer produce: a different subscription, or a differently named group. Either way the URL is registered as an Entra redirect URI and Entra matches it as an exact string. A default cannot reference a var, hence the empty sentinel.')
@maxLength(24)
param storageAccountName string = ''

var effectiveStorageAccountName = empty(storageAccountName) ? 'st${namePrefix}${environmentName}${nameSuffix}' : storageAccountName

@description('Database name.')
param sqlDatabaseName string = 'sqldb-${namePrefix}-${environmentName}'

@description('Tags applied to every resource.')
param tags object = {
  project: 'coupon-service'
  environment: environmentName
  managedBy: 'azure-pipelines'
}

// ---------------------------------------------------------------------------
// Identity (Day 0 app registrations — see approach.md §7)
// ---------------------------------------------------------------------------

@description('Entra tenant. Defaults to the tenant of the deploying subscription.')
param tenantId string = subscription().tenantId

@description('Application (client) ID of the coupon-api registration. This is the audience the App Service validates and the resource API Management requests a token for.')
param apiClientId string

// ---------------------------------------------------------------------------
// SQL administration
// ---------------------------------------------------------------------------

@description('OBJECT ID of the principal that runs the pipeline, set as the Entra administrator of the SQL server so the grant stage can create the contained user. Object ID here — the client ID form applies to the SQL contained user, not to the server administrator.')
param deployingPrincipalObjectId string

@description('Display name recorded for the SQL Entra administrator. Cosmetic; it is the object ID that grants access.')
param sqlAdminLogin string

// ---------------------------------------------------------------------------
// API Management
// ---------------------------------------------------------------------------

@description('Publisher email recorded on the API Management service.')
param apimPublisherEmail string

@description('Publisher name recorded on the API Management service.')
param apimPublisherName string = 'Coupon Service'

@description('Name of the APIM subscription the pipeline reads a key from at smoke-test time. The key itself is generated by APIM and never stored in a file.')
param apimSubscriptionName string = 'smoke-test'

@description('Name of the APIM subscription the React frontend uses. Separate from the smoke-test subscription so the two are independently revocable — the frontend key is embedded in a public bundle and the smoke test key is not.')
param frontendSubscriptionName string = 'frontend'

// ---------------------------------------------------------------------------
// Modules
// ---------------------------------------------------------------------------

module identity 'modules/identity.bicep' = {
  name: 'identity'
  params: {
    location: location
    apiIdentityName: apiIdentityName
    gatewayIdentityName: gatewayIdentityName
    tags: tags
  }
}

module monitoring 'modules/monitoring.bicep' = {
  name: 'monitoring'
  params: {
    location: location
    logAnalyticsName: logAnalyticsName
    appInsightsName: appInsightsName
    tags: tags
  }
}

module storage 'modules/storage.bicep' = {
  name: 'storage'
  params: {
    location: location
    storageAccountName: effectiveStorageAccountName
    tags: tags
  }
}

module sql 'modules/sql.bicep' = {
  name: 'sql'
  params: {
    location: location
    sqlServerName: sqlServerName
    sqlDatabaseName: sqlDatabaseName
    tenantId: tenantId
    sqlAdminObjectId: deployingPrincipalObjectId
    sqlAdminLogin: sqlAdminLogin
    tags: tags
  }
}

module appService 'modules/appservice.bicep' = {
  name: 'appService'
  params: {
    location: location
    appServicePlanName: appServicePlanName
    appServiceName: appServiceName
    apiIdentityResourceId: identity.outputs.apiIdentityResourceId
    apiIdentityClientId: identity.outputs.apiIdentityClientId
    gatewayIdentityClientId: identity.outputs.gatewayIdentityClientId
    sqlServerFqdn: sql.outputs.sqlServerFqdn
    sqlDatabaseName: sql.outputs.sqlDatabaseName
    appInsightsConnectionString: monitoring.outputs.appInsightsConnectionString
    logAnalyticsResourceId: monitoring.outputs.logAnalyticsResourceId
    tenantId: tenantId
    apiClientId: apiClientId
    tags: tags
  }
}

module apim 'modules/apim.bicep' = {
  name: 'apim'
  params: {
    location: location
    apimServiceName: apimServiceName
    apimPublisherEmail: apimPublisherEmail
    apimPublisherName: apimPublisherName
    apimSubscriptionName: apimSubscriptionName
    frontendSubscriptionName: frontendSubscriptionName
    gatewayIdentityResourceId: identity.outputs.gatewayIdentityResourceId
    gatewayIdentityClientId: identity.outputs.gatewayIdentityClientId
    backendUrl: 'https://${appService.outputs.appServiceDefaultHostName}/api/v1'
    // The bare application (client) ID, which is the form the authentication-managed-identity
    // documentation uses for a caller's own Entra application. The App Service accepts both
    // this and the api:// URI as audiences, so the token validates either way.
    backendResource: apiClientId
    tenantId: tenantId
    apiClientId: apiClientId
    frontendOrigin: storage.outputs.staticWebsiteOrigin
    appInsightsResourceId: monitoring.outputs.appInsightsResourceId
    appInsightsConnectionString: monitoring.outputs.appInsightsConnectionString
    logAnalyticsResourceId: monitoring.outputs.logAnalyticsResourceId
    tags: tags
  }
}

// ---------------------------------------------------------------------------
// Outputs — consumed by the pipeline. Nothing secret appears here; the APIM
// subscription key is read at smoke-test time via listSecrets, not emitted.
// ---------------------------------------------------------------------------

@description('App Service name, for the deploy stage.')
output appServiceName string = appService.outputs.appServiceName

@description('App Service default hostname. Direct access returns 401 — the gateway is the only way in.')
output appServiceDefaultHostName string = appService.outputs.appServiceDefaultHostName

@description('Client ID of the App Service identity. The grant stage converts this to a little-endian byte literal and uses it as the SQL contained-user SID.')
output apiIdentityClientId string = identity.outputs.apiIdentityClientId

@description('Name of the App Service identity, used verbatim as the SQL contained-user name.')
output apiIdentityName string = identity.outputs.apiIdentityName

@description('Fully qualified SQL server name, for the grant stage.')
output sqlServerFqdn string = sql.outputs.sqlServerFqdn

@description('Database name, for the grant stage.')
output sqlDatabaseName string = sql.outputs.sqlDatabaseName

@description('APIM service name, for reading the subscription key at smoke-test time.')
output apimServiceName string = apim.outputs.apimServiceName

@description('Gateway base URL. The smoke test calls this, never the App Service.')
output apimGatewayUrl string = apim.outputs.apimGatewayUrl

@description('Name of the APIM subscription whose key the smoke test uses.')
output apimSubscriptionName string = apim.outputs.apimSubscriptionName

@description('Name of the APIM subscription whose key is compiled into the frontend bundle.')
output frontendSubscriptionName string = apim.outputs.frontendSubscriptionName

@description('Storage account holding the static frontend.')
output storageAccountName string = storage.outputs.storageAccountName

@description('Static website origin, no trailing slash. Phase E compares this against the registered Entra redirect URI and fails if they differ.')
output frontendOrigin string = storage.outputs.staticWebsiteOrigin
